module.exports = {
    aor: {
        action: {
            delete: 'Видалити',
            show: 'Перегляд',
            list: 'Список',
            save: 'Зберегти',
            create: 'Створити',
            edit: 'Редагувати',
            cancel: 'Скасувати',
            refresh: 'Оновити',
            add_filter: 'Добавити фільтр',
            remove_filter: 'Видалити фільтр',
        },
        boolean: {
            true: 'Так',
            false: 'Ні',
        },
        page: {
            list: '%{name}',
            edit: '%{name} #%{id}',
            show: '%{name} #%{id}',
            create: 'Створити %{name}',
            delete: 'Видалити %{name} #%{id}',
            dashboard: 'Головна',
        },
        input: {
            image: {
                upload_several: 'Перенесіть файли сюди або натисніть для вибору.',
                upload_single: 'Перенесіть файл сюди або натисніть для вибору.',
            },
        },
        message: {
            yes: 'Так',
            no: 'Ні',
            are_you_sure: 'Ви впевнені?',
            about: 'Довідка',
        },
        navigation: {
            no_results: 'Результатів не знайдено',
            page_out_of_boundaries: 'Сторінка %{page} за межами',
            page_out_from_end: 'Неможливо переиіститись дальше останньої сторінки',
            page_out_from_begin: 'Номер сторінки не може бути меншим ніж 1',
            page_range_info: '%{offsetBegin}-%{offsetEnd} з %{total}',
            next: 'Наступна',
            prev: 'Попередня',
        },
        auth: {
            username: 'І\'мя користувача',
            password: 'Пароль',
            sign_in: 'Вхід',
            sign_in_error: 'Помилка авторизації, спробуйте ще раз',
            logout: 'Вийти',
        },
        notification: {
            updated: 'Елемент оновлено',
            created: 'Елемент створено',
            deleted: 'Елемент видалино',
            item_doesnt_exist: 'Елемент не існує',
            http_error: 'Помилка сервера',
        },
        validation: {
            required: 'Обов\'язково для заповнення',
            minLength: 'Мінімальна кіл-сть символів %{min}',
            maxLength: 'Максимальна кіл-сть символів %{max}',
            minValue: 'Мінімальне значенння %{min}',
            maxValue: 'Значення може бути %{max} або менше',
            number: 'Має бути цифрою',
            email: 'Не коректний email',
        },
    },
};
